version: '3.8'
services:
  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "5050:5050"
    env_file:
      - .env.docker
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  celery_worker:
    build: .
    command: celery -A tasks.celery_app.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      - redis 