version: '3.8'
services:
  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
      - ./official_models:/root/.paddlex/official_models
    ports:
      - "5050:5000"
    env_file:
      - .env.docker
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  celery_worker:
    build: .
    command: celery -A tasks.celery_app.celery_app worker --loglevel=info
    volumes:
      - .:/app
      - ./official_models:/root/.paddlex/official_models
    env_file:
      - .env.docker
    depends_on:
      - redis 